import * as db from './db.js';
import {compactPhotoLines,directionLabel,readingAt,validateGroup,move,digest,tar,untar,localDay,validDay,workDayOf,numberedPhoto,numberedGroup,previewRotation,zoomCapability,snapZoom,cropRect} from './core.js';
const $=id=>document.getElementById(id),say=s=>$('status').textContent=s;
let photos=[],assets=[],groups=[],selected=new Set(),multi=false,edit=null,editBaseline=null,urls={gallery:[],groups:[],order:[]},stream=null,watch=null,gps=null,heading=null,sensorState='尚未啟用',active='camera',starting=false,busy=false,rotating=false,cameraSession=0,zoomState=null,directionStatus='尚未啟用',gpsStatus='尚未啟用';
const text=(tag,s)=>{const e=document.createElement(tag);e.textContent=s;return e;};
async function run(fn){try{await fn();}catch(e){say('操作／儲存失敗：'+e.message+'。資料未宣稱成功，請重試或先備份。');}}
const DAY_KEY='field-photo-notebook-work-days';
function readDays(){try{const d=JSON.parse(localStorage.getItem(DAY_KEY)||'{}');return {active:validDay(d.active)?d.active:null,days:Array.isArray(d.days)?d.days.filter(validDay):[]};}catch{return {active:null,days:[]};}}
let dayState=readDays(),activeDay=dayState.active;
const previewCache=new Map(),rotations=new Map();
function rememberDay(day){const next={active:day,days:[...new Set([...dayState.days,day])].sort()};localStorage.setItem(DAY_KEY,JSON.stringify(next));dayState=next;activeDay=day;}
async function load(){await db.ensurePhotoIdentities();({photos,assets,groups}=await db.snapshot());photos.sort((a,b)=>photoTime(a)-photoTime(b)||(a.photoNumber??0)-(b.photoNumber??0)||a.id.localeCompare(b.id));if(!activeDay)rememberDay(photos.length?workDayOf(photos.at(-1)):localDay());render();}
const photoTime=p=>p.buttonPressedAt??p.capturedAt??p.importedAt??0;
const photoLabel=p=>p?numberedPhoto(p):'照片未取得';
const groupTitle=ids=>numberedGroup(ids,photos);
const dayPhotos=()=>photos.filter(p=>workDayOf(p)===activeDay);
const groupInDay=g=>g.workDay===activeDay||g.photoIds.some(id=>photos.some(p=>p.id===id&&workDayOf(p)===activeDay));
function releaseImages(pool){urls[pool].forEach(URL.revokeObjectURL);urls[pool]=[];}
function photoImage(id,pool){const a=assets.find(a=>a.id===id),p=photos.find(p=>p.id===id);if(!a)return text('p','原始影像未取得');const im=document.createElement('img');im.loading='lazy';im.alt=photoLabel(p);const key=`${id}:${p.displayRotation??'auto'}`;if(previewCache.has(key)){im.src=previewCache.get(key);im.dataset.previewReady='true';im.dataset.rotation=p.displayRotation??rotations.get(id)??0;return im;}im.onerror=()=>{im.dataset.previewReady='true';im.dataset.previewError='true';im.alt=photoLabel(p)+'（原圖無法解碼，未刪除）';};im.src=URL.createObjectURL(a.original);urls[pool].push(im.src);im.onload=()=>{im.onload=null;try{const w=im.naturalWidth,h=im.naturalHeight,r=previewRotation(p,w,h);rotations.set(id,r);const swapped=r%180!==0,ow=swapped?h:w,oh=swapped?w:h,scale=Math.min(1,960/Math.max(ow,oh)),c=document.createElement('canvas');c.width=Math.max(1,Math.round(ow*scale));c.height=Math.max(1,Math.round(oh*scale));const ctx=c.getContext('2d');ctx.translate(c.width/2,c.height/2);ctx.rotate(r*Math.PI/180);ctx.drawImage(im,-w*scale/2,-h*scale/2,w*scale,h*scale);const result=c.toDataURL('image/jpeg',.9);if(previewCache.size>=60)previewCache.delete(previewCache.keys().next().value);previewCache.set(key,result);if(im.isConnected)im.src=result;im.dataset.rotation=r;im.dataset.previewReady='true';}catch{im.dataset.previewReady='true';say('此照片無法產生旋轉預覽；原圖仍保留。');}};return im;}
function photoInfo(p){const box=text('div','');box.className='photo-info';for(const line of compactPhotoLines(p,0).slice(1))box.append(text('p',line));return box;}
function editorValue(){return edit?JSON.stringify({photoIds:edit.photoIds,engineering:$('engineering').value}):null;}
function editorDirty(){return !!edit&&editorValue()!==editBaseline;}
function canDiscardEditor(){return !editorDirty()||confirm('記事尚未儲存，確定放棄這次編輯？');}
window.addEventListener('beforeunload',e=>{if(editorDirty()||pending.length||busy||rotating){e.preventDefault();e.returnValue='';}});
function stop(){cameraSession++;stream?.getTracks().forEach(t=>t.stop());stream=null;$('video').srcObject=null;if(watch!==null)navigator.geolocation.clearWatch(watch);watch=null;gps=null;heading=null;zoomState?.cancelFrame?.();zoomState=null;directionStatus=gpsStatus='已停止';window.removeEventListener('deviceorientation',onOrientation);window.removeEventListener('deviceorientationabsolute',onOrientation);sensorState='感測已停止';zoomUI();sensors();}
function sensors(){ $('sensor').textContent=`${sensorState}；GPS 狀態：${gpsStatus}；方向狀態：${directionStatus}；GPS：${gps?`${gps.latitude.toFixed(6)}, ${gps.longitude.toFixed(6)} ±${gps.accuracyM}m；${Date.now()-gps.readingAt<=10000?'新鮮':'過期'}；${gps.accuracyM>20?'約略':'精度非保證'}`:'未取得'}；裝置羅盤：${heading?`裝置參考推估：${directionLabel(heading.degrees)}；${heading.degrees.toFixed(1)}°；${heading.quality}；${Date.now()-heading.readingAt<=2000?'新鮮':'過期'}（僅供參考）`:'未取得絕對方位'}；鏡頭朝向：無法可靠判定` ;}
setInterval(sensors,1000);
function tab(name){if(name==='editor'&&!edit)return;if(name!=='camera')stop();active=name;for(const n of ['camera','photos','groups'])$(n).hidden=n!==name;$('editor').hidden=name!=='editor'||!edit;$('editingTab').hidden=$('appendToEditor').hidden=!edit;document.querySelectorAll('[data-tab]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.tab===name));if(name==='editor'){renderOrder();$('editor').scrollIntoView({block:'start'});const h=$('editor').querySelector('h2');h.tabIndex=-1;h.focus({preventScroll:true});}}
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>tab(b.dataset.tab));
function currentCamera(session){return session===cameraSession&&active==='camera'&&!document.hidden;}
function beginDirection(session){const E=window.DeviceOrientationEvent;if(!E){directionStatus='不支援方向感測';sensors();return;}directionStatus='等待方向授權';let permission;try{permission=typeof E.requestPermission==='function'?E.requestPermission(true):Promise.resolve('granted');}catch(e){permission=Promise.reject(e);}Promise.resolve(permission).then(result=>{if(!currentCamera(session))return;if(result!=='granted'){directionStatus='方向權限被拒絕';sensors();return;}window.addEventListener('deviceorientation',onOrientation);window.addEventListener('deviceorientationabsolute',onOrientation);directionStatus='已啟用，等待絕對方位讀值';sensors();},e=>{if(currentCamera(session)){directionStatus='方向授權失敗：'+e.message;sensors();}});}
function previewDimensions(){const v=$('video');if(stream&&v.videoWidth&&v.videoHeight)$('cameraPreview').style.setProperty('--camera-aspect',v.videoWidth/v.videoHeight);}
$('video').addEventListener('loadedmetadata',previewDimensions);$('video').addEventListener('resize',previewDimensions);
function zoomUI(){const z=zoomState,disabled=!z||z.applying||busy;for(const id of ['zoom','zoomIn','zoomOut'])$(id).disabled=disabled;$('zoom').disabled=!z||busy;$('start').disabled=starting||busy;$('shutter').disabled=!stream||starting||busy||!!z?.applying||z?.factor===null||z?.frameReady===false;if(!z){$('zoomValue').textContent='開啟相機後可縮放';$('zoomNote').textContent='支援時使用鏡頭 API；否則使用數位裁切，畫質會降低。';$('video').style.transform='none';return;}$('zoom').min=z.range.min;$('zoom').max=z.range.max;$('zoom').step=z.range.step;$('zoom').value=z.requested??z.factor??z.range.min;$('zoomValue').textContent=z.applying?'正在套用縮放…':z.factor===null?'倍率未確認，請重新開啟':`${Number(z.factor.toFixed(2))}×`;$('zoomNote').textContent=z.mode==='camera-api'?'鏡頭 API 縮放（不保證光學）；變焦拍攝保存目前影格 JPEG，解析度依手機。':'數位裁切（非光學）：預覽與新照片一同裁切，放大越多解析度越低。';$('video').style.transform=z.mode==='browser-digital-crop'?`scale(${z.factor})`:'none';if(z.factor===null)for(const id of ['zoom','zoomIn','zoomOut'])$(id).disabled=true;}
function initZoom(track,session,settings){let cap=null;try{cap=track.getCapabilities?.();}catch{}const range=zoomCapability(cap,settings.zoom);zoomState={track,session,mode:range?'camera-api':'browser-digital-crop',range:range??{min:1,max:4,step:.1},factor:range?settings.zoom:1,applying:false,requested:null,frameReady:true};previewDimensions();zoomUI();}
function nextZoomFrame(z){const v=$('video');return new Promise((resolve,reject)=>{let frame,tick,timer,finished=false;const done=error=>{if(finished)return;finished=true;clearTimeout(timer);if(frame!==undefined)v.cancelVideoFrameCallback?.(frame);if(tick!==undefined)cancelAnimationFrame(tick);z.cancelFrame=null;error?reject(error):resolve();};z.cancelFrame=()=>done(Error('相機已停止'));timer=setTimeout(()=>done(Error('縮放後影格未更新，請重試或重新開啟')),4000);if(v.requestVideoFrameCallback)frame=v.requestVideoFrameCallback(()=>done());else{const before=v.currentTime;const check=()=>{if(v.currentTime>before)done();else tick=requestAnimationFrame(check);};tick=requestAnimationFrame(check);}});}
async function requestZoom(value){const z=zoomState;if(!z||busy||z.factor===null)return;z.requested=snapZoom(value,z.range);if(z.applying)return;z.applying=true;zoomUI();try{while(z.requested!==null&&zoomState===z&&currentCamera(z.session)){const next=z.requested;z.requested=null;if(z.mode==='camera-api'){await z.track.applyConstraints({advanced:[{zoom:next}]});if(zoomState!==z||!currentCamera(z.session))return;const actual=z.track.getSettings().zoom;if(!Number.isFinite(actual)||actual<z.range.min||actual>z.range.max){z.factor=null;throw Error('手機未回報可確認的倍率');}z.factor=actual;z.frameReady=false;await nextZoomFrame(z);if(zoomState!==z||!currentCamera(z.session))return;z.frameReady=true;if(Math.abs(actual-next)>Math.max(1e-6,z.range.step/2))throw Error('手機未套用要求倍率，顯示仍以實際讀值為準');}else z.factor=next;}}catch(e){if(zoomState===z&&currentCamera(z.session)){if(z.mode==='camera-api'){try{const actual=z.track.getSettings().zoom;const valid=Number.isFinite(actual)&&actual>=z.range.min&&actual<=z.range.max;if(!valid||actual!==z.factor)z.frameReady=false;z.factor=valid?actual:null;}catch{z.factor=null;z.frameReady=false;}}z.requested=null;say('縮放未成功：'+e.message+'；未宣稱已放大，可重新開啟相機。');}}finally{z.applying=false;if(zoomState===z)zoomUI();}}
$('zoom').oninput=()=>run(()=>requestZoom(Number($('zoom').value)));$('zoomIn').onclick=()=>run(()=>requestZoom((zoomState?.factor??1)+Math.max(zoomState?.range.step??.1,.5)));$('zoomOut').onclick=()=>run(()=>requestZoom((zoomState?.factor??1)-Math.max(zoomState?.range.step??.1,.5)));
$('start').onclick=()=>run(async()=>{
  if(starting||busy||active!=='camera')return;
  starting=true;
  let acquired=null,session;
  try{
    stop();session=cameraSession;zoomUI();
    if(!isSecureContext)throw Error('相機需要 HTTPS 或 localhost');
    // iOS needs requestPermission directly inside this click, before any await.
    beginDirection(session);
    acquired=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},aspectRatio:{ideal:4/3},width:{ideal:1600},height:{ideal:1200}},audio:false});
    if(!currentCamera(session)){acquired.getTracks().forEach(t=>t.stop());return;}
    stream=acquired;$('video').srcObject=acquired;
    await $('video').play();
    if(!currentCamera(session)){acquired.getTracks().forEach(t=>t.stop());return;}
    const track=acquired.getVideoTracks()[0],settings=track.getSettings();
    sensorState='實際鏡頭：'+(settings.facingMode||'未知');initZoom(track,session,settings);
    gpsStatus=navigator.geolocation?'等待定位授權／讀值':'不支援定位';
    if(navigator.geolocation)watch=navigator.geolocation.watchPosition(p=>{
      if(!currentCamera(session))return;const c=p.coords;
      if(Number.isFinite(c.latitude)&&Number.isFinite(c.longitude)&&Number.isFinite(c.accuracy)){gps={latitude:c.latitude,longitude:c.longitude,accuracyM:c.accuracy,readingAt:p.timestamp,receivedAt:Date.now(),source:'browser-geolocation',precision:c.accuracy>20?'約略':'非保證'};gpsStatus='已取得定位';}sensors();
    },e=>{if(!currentCamera(session))return;gps=null;gpsStatus='定位未取得：'+e.message;sensors();},{enableHighAccuracy:true,maximumAge:0,timeout:15000});sensors();
  }catch(e){acquired?.getTracks().forEach(t=>t.stop());if(session===cameraSession){stop();throw e;}}
  finally{starting=false;zoomUI();}
});
$('stop').onclick=stop;document.addEventListener('visibilitychange',()=>{if(document.hidden)stop();});window.addEventListener('pagehide',stop);
function onOrientation(e){let degrees,source;if(Number.isFinite(e.webkitCompassHeading)&&e.webkitCompassHeading>=0){degrees=e.webkitCompassHeading;source='webkitCompassHeading';}else if(e.absolute===true&&Number.isFinite(e.alpha)){degrees=(360-e.alpha)%360;source='absolute-alpha-device-reference';}else{if(!heading)directionStatus='相對旋轉不是絕對羅盤';return;}directionStatus='已取得裝置參考（需驗證）';heading={degrees,source,readingAt:Date.now(),timestampMeaning:'瀏覽器收到讀值時間（非硬體時間）',accuracy:Number.isFinite(e.webkitCompassAccuracy)?e.webkitCompassAccuracy:null,quality:Number.isFinite(e.webkitCompassAccuracy)&&e.webkitCompassAccuracy<0?'平台回報不可靠':'精度未保證／僅供參考',northReference:'平台絕對參考；真北／磁北未保證',alpha:e.alpha,beta:e.beta,gamma:e.gamma,screenAngle:screen.orientation?.angle??window.orientation??null,cameraBearing:null,cameraTransformEvidence:'未驗證裝置／螢幕／鏡頭轉換'};}
let pending=[];
async function commitPending(){while(pending.length){const item=pending[0];say('正在儲存原始影像…');await db.savePhoto(item.photo,item.blob);pending.shift();}await load();say('已儲存於本機（未上傳）');}
const retry=text('button','重試未完成照片儲存');retry.onclick=()=>run(commitPending);$('camera').append(retry);
function buttonReading(reading,time,limit){
  const sample=readingAt(reading,time,limit);
  if(!sample)return null;
  const {ageAtShutterMs,...rest}=sample;
  return {...rest,ageAtButtonPressMs:ageAtShutterMs,freshnessReference:'按下拍照按鈕時間；不是曝光時間'};
}
function completionReading(reading,time,limit){
  return reading?{...reading,ageAtAcquisitionCompletedMs:time-reading.readingAt,freshnessAtAcquisitionCompleted:time-reading.readingAt<=limit?'新鮮':'過期'}:null;
}
$('shutter').onclick=()=>run(async()=>{
  if(busy||!stream||zoomState?.applying||zoomState?.factor===null||zoomState?.frameReady===false)return;
  // Timestamp the actual gesture, before any queued storage work.
  const buttonPressedAt=Date.now(),session=cameraSession,track=stream.getVideoTracks()[0],workDay=activeDay,screenAngle=screen.orientation?.angle??window.orientation??null;
  const location=buttonReading(gps,buttonPressedAt,10000),direction=buttonReading(heading,buttonPressedAt,2000);
  const missing=[];if(!location||location.freshness==='過期')missing.push('GPS 未取得或過期');if(!direction||direction.freshness==='過期'||direction.accuracy<0)missing.push('方向未取得、過期或不可靠');if(missing.length&&!confirm(missing.join('；')+'。建議等待讀值／重新開啟。仍要拍照並保存缺值或未確認資料？'))return;
  const z=zoomState,captureSettings=track.getSettings(),reportedZoom=Number.isFinite(captureSettings.zoom)?captureSettings.zoom:null,zoom={mode:z?.mode??'unknown',factor:z?.mode==='camera-api'?reportedZoom:(z?.factor??null),reportedTrackZoom:reportedZoom,meaning:'API 倍率非光學認證；數位倍率為目前影格的中央裁切；曝光時間未知'},useZoomFrame=zoom.factor!==1;
  if(z?.mode==='camera-api'&&!zoomCapability({zoom:z.range},reportedZoom)){z.factor=null;z.frameReady=false;zoomUI();throw Error('拍照時相機未回報有效倍率，請重新開啟');}
  busy=true;zoomUI();
  try{
    if(pending.length)await commitPending();
    if(session!==cameraSession||track.readyState==='ended')throw Error('相機已停止，請重新開啟後拍攝');
    const acquisitionStartedAt=Date.now();let blob,method,frameCopiedAt=null,outputWidth=null,outputHeight=null;
    try{
      if(useZoomFrame||!window.ImageCapture)throw Error();
      blob=await new ImageCapture(track).takePhoto();method='ImageCapture.takePhoto';
    }catch(e){
      if(session!==cameraSession||track.readyState==='ended')throw Error('相機已停止，未擷取影像');
      const v=$('video');if(!v.videoWidth)throw Error('相機影格尚未就緒');
      const crop=cropRect(v.videoWidth,v.videoHeight,zoom.mode==='browser-digital-crop'?zoom.factor:1),c=document.createElement('canvas');c.width=crop.width;c.height=crop.height;
      c.getContext('2d').drawImage(v,crop.sx,crop.sy,crop.sw,crop.sh,0,0,c.width,c.height);frameCopiedAt=Date.now();outputWidth=c.width;outputHeight=c.height;
      blob=await new Promise(r=>c.toBlob(r,'image/jpeg',.92));method=useZoomFrame?'變焦瀏覽器影格擷取（數位／API 縮放，非 RAW）':'瀏覽器影格擷取（非 RAW／感光元件原檔）';
    }
    const acquisitionCompletedAt=Date.now();
    if(!blob)throw Error('未取得影像');
    const id=crypto.randomUUID();
    pending.push({blob,photo:{id,source:'camera',capturedAt:null,buttonPressedAt,acquisitionStartedAt,acquisitionCompletedAt,frameCopiedAt,
      timingMeaning:'曝光時間未知；按鈕／呼叫開始／Blob 取得／影格複製均為瀏覽器裝置時鐘，非硬體曝光時間',
      importedAt:null,originalName:id+(blob.type==='image/png'?'.png':blob.type==='image/webp'?'.webp':'.jpg'),mime:blob.type,captureMethod:method,
      location:completionReading(location,acquisitionCompletedAt,10000),heading:completionReading(direction,acquisitionCompletedAt,2000),
      cameraFacing:captureSettings.facingMode??'unknown',cameraBearing:null,workDay,screenAngle,zoom,outputWidth,outputHeight}});
    await commitPending();
  }finally{busy=false;zoomUI();}
});
$('import').onchange=()=>run(async()=>{const workDay=activeDay;for(const file of $('import').files){if(!file.type.startsWith('image/'))throw Error('請選取影像');pending.push({blob:file,photo:{id:crypto.randomUUID(),source:'gallery',originalName:file.name,mime:file.type,capturedAt:null,importedAt:Date.now(),fileLastModifiedAt:file.lastModified,location:null,heading:null,sourceExif:null,workDay,captureMethod:'原始檔案匯入；未解析 EXIF，預覽由瀏覽器解碼方向' }});}await commitPending();$('import').value='';});
function choose(id){if(multi){selected.has(id)?selected.delete(id):selected.add(id);}else selected=selected.has(id)?new Set():new Set([id]);render();}
function render(){$('editingTab').hidden=$('appendToEditor').hidden=!edit;releaseImages('gallery');releaseImages('groups');$('gallery').replaceChildren();const days=[...new Set([...dayState.days,...photos.map(workDayOf),activeDay])].filter(validDay).sort();$('workDay').replaceChildren();for(const d of days){const o=text('option',`${d}（${photos.filter(p=>workDayOf(p)===d).length} 張）`);o.value=d;$('workDay').append(o);}$('workDay').value=activeDay;$('currentDay').textContent=`工作日：${activeDay}；編號按工作日獨立且不因刪除重新編排`;for(const id of selected)if(!dayPhotos().some(p=>p.id===id))selected.delete(id);const assigned=new Set(groups.flatMap(g=>g.photoIds));for(const p of dayPhotos().filter(p=>!assigned.has(p.id)||selected.has(p.id))){const card=text('div','');card.className='card';const b=text('button',`${selected.has(p.id)?'☑':'□'} ${photoLabel(p)} · ${p.source==='camera'?'拍攝':'相簿匯入'}`);b.setAttribute('aria-pressed',selected.has(p.id));b.prepend(photoImage(p.id,'gallery'));let timer,long=false;b.onpointerdown=e=>{if(e.button!==0)return;long=false;timer=setTimeout(()=>{long=true;multi=true;selected.add(p.id);render();},550);};b.onpointerup=b.onpointerleave=b.onpointercancel=()=>clearTimeout(timer);b.onclick=()=>{if(long){long=false;return;}choose(p.id);};card.append(b);$('gallery').append(card);}$('multi').textContent=multi?'結束多選':'選取多張';$('multi').setAttribute('aria-pressed',multi);$('selectionCount').textContent=`已選 ${selected.size} 張；本日待整理 ${dayPhotos().filter(p=>!assigned.has(p.id)).length} 張`;$('appendToEditor').disabled=$('deleteSelected').disabled=$('rotateLeft').disabled=$('rotateRight').disabled=!selected.size;$('groupList').replaceChildren();if(!groups.some(groupInDay))$('groupList').append(text('p','本工作日尚無紀錄集。請到待整理照片選取照片並記事。'));for(const g of groups.filter(groupInDay)){const a=text('article','');a.append(text('h3',groupTitle(g.photoIds)),text('p',`${g.photoIds.length} 張 · 更新 ${new Date(g.updatedAt).toLocaleString()}`));const strip=text('div','');strip.className='group-photos';g.photoIds.forEach((id,i)=>{const p=photos.find(p=>p.id===id),figure=text('figure','');figure.append(photoImage(id,'groups'),text('figcaption',compactPhotoLines(p,i)[0]));strip.append(figure);});a.append(strip);g.photoIds.forEach((id,i)=>{const row=text('div','');row.append(text('strong',compactPhotoLines(photos.find(p=>p.id===id),i)[0]),photoInfo(photos.find(p=>p.id===id)));a.append(row);});for(const [label,value] of [['工程描述',g.engineering]]){const note=text('p',`${label}：${value||'未填寫'}`);note.className='note-text';a.append(note);}const e=text('button','編輯／排序照片');e.onclick=()=>openEditor(g);const d=text('button','移除紀錄集（保留原始照片）');d.onclick=()=>run(async()=>{if(edit?.id===g.id){say('請先關閉或儲存此紀錄集的編輯，再移除。');return;}if(confirm('只移除此紀錄集，原始照片仍保留？')){await db.removeGroup(g.id);await load();say('已移除紀錄集，照片仍保留');}});a.append(e,d);$('groupList').append(a);}if(edit&&active==='editor')renderOrder();}
$('multi').onclick=()=>{multi=!multi;if(!multi)selected=new Set([...selected].slice(0,1));render();};
function openEditor(g,ids=[...selected]){if(!canDiscardEditor())return;edit=structuredClone(g||{id:crypto.randomUUID(),title:'',notes:'',engineering:'',photoIds:ids,createdAt:Date.now(),workDay:activeDay});$('title').value=groupTitle(edit.photoIds);$('engineering').value=edit.engineering;editBaseline=editorValue();tab('editor');}
function renderOrder(focus){$('title').value=groupTitle(edit.photoIds);releaseImages('order');$('order').replaceChildren();$('photoInfo').replaceChildren();const previews=text('div','');previews.className='editor-previews';previews.dataset.count=edit.photoIds.length;edit.photoIds.forEach((id,i)=>{const figure=text('figure','');figure.append(photoImage(id,'order'),text('figcaption',compactPhotoLines(photos.find(p=>p.id===id),i)[0]));previews.append(figure);});$('order').append(previews);edit.photoIds.forEach((id,i)=>{const p=photos.find(p=>p.id===id),row=text('article',''),head=text('div',''),controls=text('div','');head.className='photo-row-head';controls.className='photo-row-controls';head.append(text('h3',compactPhotoLines(p,i)[0]));for(const [label,delta] of [['上移',-1],['下移',1]]){const b=text('button',delta<0?'↑':'↓');b.title=label;b.setAttribute('aria-label',`${i+1}. ${photoLabel(p)} ${label}`);b.dataset.photoId=id;b.dataset.action=label;b.disabled=i+delta<0||i+delta>=edit.photoIds.length;b.onclick=()=>{edit.photoIds=move(edit.photoIds,i,delta);renderOrder({id,action:label});say(`${photoLabel(p)} 已${label}至第 ${edit.photoIds.indexOf(id)+1} 張`);};controls.append(b);}const r=text('button','×');r.title='從此組移除';r.setAttribute('aria-label',`${i+1}. ${photoLabel(p)} 從此組移除`);r.dataset.photoId=id;r.dataset.action='從此組移除';r.onclick=()=>{edit.photoIds.splice(i,1);renderOrder({id:edit.photoIds[Math.min(i,edit.photoIds.length-1)],action:'從此組移除'});say(`${photoLabel(p)} 已從此組移除，原始照片仍保留`);};controls.append(r);head.append(controls);row.append(head,photoInfo(p));$('photoInfo').append(row);});if(focus){const controls=[...$('photoInfo').querySelectorAll('button')].filter(b=>b.dataset.photoId===focus.id&&!b.disabled);(controls.find(b=>b.dataset.action===focus.action)||controls[0]||$('addSelected')).focus();}}
$('compose').onclick=()=>{if(!selected.size){say('請先選照片');return;}openEditor();};$('appendToEditor').onclick=()=>{if(!edit)return;const day=edit.workDay??workDayOf(photos.find(p=>p.id===edit.photoIds[0])??{});if([...selected].some(id=>workDayOf(photos.find(p=>p.id===id))!==day)){say('請勿將不同工作日的照片加入同一記事。');return;}edit.photoIds=[...new Set([...edit.photoIds,...selected])];tab('editor');};$('addSelected').onclick=()=>{if(edit){tab('photos');say('請選取照片，再按「加入目前記事並返回」。');}};$('cancel').onclick=()=>{if(!canDiscardEditor())return;const returnTab=groups.some(g=>g.id===edit?.id)?'groups':'photos';$('editor').hidden=true;edit=null;editBaseline=null;releaseImages('order');render();tab(returnTab);};$('save').onclick=()=>run(async()=>{if(!edit)return;const title=groupTitle(edit.photoIds),g={...edit,title,notes:edit.notes??'',engineering:$('engineering').value,updatedAt:Date.now()};if(edit.title&&edit.title!==title&&!edit.legacyTitle)g.legacyTitle=edit.title;validateGroup(g,new Set(photos.map(p=>p.id)));await db.saveGroup(g);$('editor').hidden=true;edit=null;editBaseline=null;releaseImages('order');selected.clear();await load();say('紀錄集已儲存');tab('groups');});
$('backup').onclick=()=>run(async()=>{say('正在建立本機備份（交易快照；不含未提交資料）…');const snapshot=await db.snapshot();const entries=[],records=[];for(const p of snapshot.photos){const blob=snapshot.assets.find(a=>a.id===p.id)?.original;if(!blob)throw Error('原始影像缺失');const path=`originals/${p.id}.bin`;entries.push([path,blob]);records.push({...p,path,size:blob.size,sha256:await digest(blob)});}for(const g of snapshot.groups)validateGroup(g,new Set(snapshot.photos.map(p=>p.id)));const manifest={schema:1,createdAt:Date.now(),snapshotStartedAt:snapshot.startedAt,snapshotCompletedAt:snapshot.completedAt,completeness:'單一唯讀交易中的已提交資料；不含未儲存表單／待存照片／快照之後提交資料',photos:records,groups:snapshot.groups,workDays:dayState.days,activeWorkDay:activeDay??localDay(),numberCounters:db.numberCounters()};entries.push(['manifest.json',new Blob([JSON.stringify(manifest,null,2)],{type:'application/json'})],['notes.txt',new Blob([snapshot.groups.map(g=>`${g.title}\n工作日：${g.workDay??'舊版請參照各照片 workDay'}\n工程描述：${g.engineering}\n${g.notes?'舊版備註（保留）：'+g.notes+'\n':''}${g.legacyTitle?'舊版名稱（保留）：'+g.legacyTitle+'\n':''}順序：${g.photoIds.join(', ')}\n`).join('\n')])],['README.txt',new Blob(['原始影像在 originals/；檔名與 MIME 在 manifest.json。GPS 是裝置位置；方向不是可靠鏡頭朝向。相機讀值以按鈕時間為基準，不是曝光資料。舊版 capturedAt / ageAtShutterMs 亦是按鈕時間／年齡。沒有 EXIF 嵌入或雲端同步。'])]);const archive=await tar(entries),url=URL.createObjectURL(archive),a=document.createElement('a');a.href=url;a.download=`field-notebook-${Date.now()}.tar`;a.click();setTimeout(()=>URL.revokeObjectURL(url),60000);say('已交給瀏覽器下載；請確認下載完成（無法驗證使用者是否取消）');});
$('restore').onchange=()=>run(async()=>{const file=$('restore').files[0];if(!file)return;say('驗證備份中…');const entries=await untar(file),m=JSON.parse(await entries.get('manifest.json')?.text());if(m.schema!==1||!Array.isArray(m.photos)||!Array.isArray(m.groups))throw Error('不支援的備份');if(m.workDays!==undefined&&(!Array.isArray(m.workDays)||m.workDays.some(d=>!validDay(d))))throw Error('工作日格式無效');if(m.activeWorkDay!==undefined&&!validDay(m.activeWorkDay))throw Error('目前工作日格式無效');if(m.numberCounters!==undefined&&(typeof m.numberCounters!=='object'||m.numberCounters===null||Array.isArray(m.numberCounters)||Object.entries(m.numberCounters).some(([d,n])=>!validDay(d)||!Number.isSafeInteger(n)||n<1)))throw Error('編號計數格式無效');const incomingNumbers=new Set();const ids=new Set(),gids=new Set(),staged=[];for(const p of m.photos){if(p.workDay!==undefined&&!validDay(p.workDay)||p.photoNumber!==undefined&&(!Number.isSafeInteger(p.photoNumber)||p.photoNumber<1)||p.displayRotation!==undefined&&![0,90,180,270].includes(p.displayRotation))throw Error('照片工作日／編號／旋轉格式無效');if(p.workDay&&p.photoNumber){const numberKey=p.workDay+':'+p.photoNumber;if(incomingNumbers.has(numberKey)||photos.some(x=>x.workDay===p.workDay&&x.photoNumber===p.photoNumber))throw Error('工作日照片編號重複或與本機衝突');incomingNumbers.add(numberKey);}if(typeof p.id!=='string'||!/^[-a-zA-Z0-9]+$/.test(p.id)||ids.has(p.id)||photos.some(x=>x.id===p.id)||p.path!==`originals/${p.id}.bin`||typeof p.originalName!=='string'||!['camera','gallery'].includes(p.source)||typeof p.mime!=='string'||!p.mime.startsWith('image/'))throw Error('照片格式／ID 重複或與本機衝突');ids.add(p.id);const b=entries.get(p.path);if(!b||b.size!==p.size||await digest(b)!==p.sha256)throw Error('影像大小或雜湊不符');const {path,size,sha256,...photo}=p;staged.push({photo,blob:new Blob([b],{type:p.mime})});}for(const g of m.groups){if(typeof g.id!=='string'||typeof g.title!=='string'||typeof g.notes!=='string'||typeof g.engineering!=='string'||gids.has(g.id)||groups.some(x=>x.id===g.id))throw Error('紀錄集格式／ID 衝突');gids.add(g.id);validateGroup(g,ids);}if(!confirm(`已驗證 ${staged.length} 張照片、${m.groups.length} 組，匯入本機？`))return;await db.transaction(['photos','assets','groups'],tx=>{for(const x of staged){tx.objectStore('photos').add(x.photo);tx.objectStore('assets').add({id:x.photo.id,original:x.blob});}for(const g of m.groups)tx.objectStore('groups').add(g);});db.mergeCounters(m.numberCounters);for(const day of m.workDays??[])if(validDay(day))dayState.days.push(day);dayState.days=[...new Set(dayState.days)];activeDay=validDay(m.activeWorkDay)?m.activeWorkDay:null;if(activeDay)rememberDay(activeDay);await load();say('備份已完整還原（原圖與顯示旋轉分開保存）');$('restore').value='';});
async function changeDay(day){if(!validDay(day))throw Error('日期請使用有效 YYYY-MM-DD');if(busy||pending.length||rotating)throw Error('請先完成照片儲存或旋轉再切換工作日');if(!canDiscardEditor()){$('workDay').value=activeDay;return;}stop();rememberDay(day);edit=null;editBaseline=null;$('editor').hidden=true;releaseImages('order');selected.clear();multi=false;if(active==='editor')tab('photos');await load();say(`已切換工作日 ${day}，其他日期照片仍保留`);}
$('workDay').onchange=()=>run(async()=>{try{await changeDay($('workDay').value);}catch(e){$('workDay').value=activeDay;throw e;}});
$('newDay').onclick=()=>run(async()=>{const day=prompt('新工作日日期（YYYY-MM-DD）。只分開整理，不清除照片，也不改拍照時間。',localDay());if(day===null)return;await changeDay(day.trim());});
$('deleteSelected').onclick=()=>run(async()=>{if(edit&&(editorDirty()||groups.some(g=>g.id===edit.id))){say('請先儲存或關閉記事，再刪除照片。');return;}const ids=[...selected];if(!ids.length)return;if(groups.some(g=>g.photoIds.some(id=>ids.includes(id))))throw Error('已有記事的照片請先移出紀錄集再刪除');if(!confirm(`永久刪除 ${ids.length} 張照片及原圖？無法復原，建議先下載完整備份。`))return;await db.deletePhotos(ids);if(edit){edit=null;editBaseline=null;$('editor').hidden=true;releaseImages('order');}for(const id of ids){rotations.delete(id);for(const k of previewCache.keys())if(k.startsWith(id+':'))previewCache.delete(k);}selected.clear();await load();say(`已永久刪除 ${ids.length} 張照片；其他照片編號不變`);});
async function rotateSelected(delta){if(rotating||!selected.size)return;rotating=true;$('rotateLeft').disabled=$('rotateRight').disabled=true;say('正在調整顯示方向…');try{for(const id of [...selected]){const p=photos.find(p=>p.id===id);let r=p.displayRotation??rotations.get(id);if(r===undefined){const a=assets.find(a=>a.id===id);const url=URL.createObjectURL(a.original);try{const im=new Image();im.src=url;await im.decode();r=previewRotation(p,im.naturalWidth,im.naturalHeight);}finally{URL.revokeObjectURL(url);}}await db.setPhotoRotation(id,(r+delta+360)%360);for(const k of previewCache.keys())if(k.startsWith(id+':'))previewCache.delete(k);}await load();say('已儲存顯示方向，原始影像位元組未改動');}finally{rotating=false;$('rotateLeft').disabled=$('rotateRight').disabled=!selected.size;}}
$('rotateLeft').onclick=()=>run(()=>rotateSelected(-90));$('rotateRight').onclick=()=>run(()=>rotateSelected(90));
$('persist').onclick=()=>run(async()=>{const ok=await navigator.storage?.persist?.();say(ok?'瀏覽器允許持續儲存，仍須備份':'未取得持續儲存保證，請備份');});
run(async()=>{await load();const s=await navigator.storage?.estimate?.();$('storage').textContent=s?`使用約 ${(s.usage/1048576).toFixed(1)} MB / 配額約 ${(s.quota/1048576).toFixed(0)} MB（可能變動）`:'無法取得配額';});
if('serviceWorker' in navigator&&isSecureContext)run(async()=>{await navigator.serviceWorker.register('./sw.js',{scope:'./'});await navigator.serviceWorker.ready;const update=()=>{$('offline').textContent=navigator.serviceWorker.controller?'離線殼已受控制；照片只存 IndexedDB，仍需備份。':'離線殼已安裝，重新載入後確認控制。';};update();navigator.serviceWorker.addEventListener('controllerchange',update);});
