import {previewRotation,validateGroup} from './core.js';

export const DOCX_MIME='application/vnd.openxmlformats-officedocument.wordprocessingml.document';
const encoder=new TextEncoder();
const crcTable=Uint32Array.from({length:256},(_,n)=>{for(let i=0;i<8;i++)n=n&1?0xedb88320^(n>>>1):n>>>1;return n>>>0;});
export function crc32(bytes){let crc=0xffffffff;for(const b of bytes)crc=crcTable[(crc^b)&255]^(crc>>>8);return (crc^0xffffffff)>>>0;}
// Standard ZIP method 0 with CRC, UTF-8 names and central directory. No fake HTML/.doc.
export async function zipStore(entries){if(entries.length>65535)throw Error('Word 檔項目過多');const parts=[],central=[],names=new Set();let offset=0,centralSize=0;for(const [name,blob] of entries){if(typeof name!=='string'||name.startsWith('/')||name.includes('\\')||name.split('/').some(p=>!p||p==='..'||p==='.')||names.has(name))throw Error('Word 封存路徑無效');names.add(name);const filename=encoder.encode(name),bytes=new Uint8Array(await blob.arrayBuffer());if(filename.length>65535||bytes.length>=0xffffffff||offset>=0xffffffff)throw Error('Word 檔過大');const crc=crc32(bytes),h=new Uint8Array(30),v=new DataView(h.buffer);v.setUint32(0,0x04034b50,true);v.setUint16(4,20,true);v.setUint16(6,0x0800,true);v.setUint16(12,33,true);v.setUint32(14,crc,true);v.setUint32(18,bytes.length,true);v.setUint32(22,bytes.length,true);v.setUint16(26,filename.length,true);parts.push(h,filename,bytes);const c=new Uint8Array(46),d=new DataView(c.buffer);d.setUint32(0,0x02014b50,true);d.setUint16(4,20,true);d.setUint16(6,20,true);d.setUint16(8,0x0800,true);d.setUint16(14,33,true);d.setUint32(16,crc,true);d.setUint32(20,bytes.length,true);d.setUint32(24,bytes.length,true);d.setUint16(28,filename.length,true);d.setUint32(42,offset,true);central.push(c,filename);centralSize+=46+filename.length;offset+=30+filename.length+bytes.length;}if(offset+centralSize>=0xffffffff)throw Error('Word 檔過大');const end=new Uint8Array(22),v=new DataView(end.buffer);v.setUint32(0,0x06054b50,true);v.setUint16(8,entries.length,true);v.setUint16(10,entries.length,true);v.setUint32(12,centralSize,true);v.setUint32(16,offset,true);return new Blob([...parts,...central,end],{type:DOCX_MIME});}
export function xmlText(value){if(typeof value!=='string')throw Error('工程描述格式無效');for(const ch of value){const n=ch.codePointAt(0);if(!(n===9||n===10||n===13||n>=32&&n<=0xd7ff||n>=0xe000&&n<=0xfffd||n>=0x10000&&n<=0x10ffff))throw Error('工程描述含無法寫入 Word 的字元');}return value.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&apos;');}
export function tablePlan(groups){if(!Array.isArray(groups)||!groups.length)throw Error('請至少選一個紀錄集');const ids=new Set(),rows=[];for(const g of groups){if(typeof g.id!=='string'||ids.has(g.id)||!Array.isArray(g.photos)||!g.photos.length)throw Error('紀錄集／照片格式無效');ids.add(g.id);xmlText(g.engineering);for(let i=0;i<g.photos.length;i+=2)rows.push({kind:'photos',groupId:g.id,photos:g.photos.slice(i,i+2),keepNext:g.photos.length<=4||i+2>=g.photos.length});rows.push({kind:'description',groupId:g.id,engineering:g.engineering});}return rows;}
const xmlHeader='<?xml version="1.0" encoding="UTF-8" standalone="yes"?>';
const relNS='http://schemas.openxmlformats.org/package/2006/relationships';
const officeRel='http://schemas.openxmlformats.org/officeDocument/2006/relationships';
const W='http://schemas.openxmlformats.org/wordprocessingml/2006/main';
const pProps=keep=>`<w:pPr><w:spacing w:before="0" w:after="0"/>${keep?'<w:keepNext/>':''}</w:pPr>`;
function descriptionParagraph(s){return `<w:p>${pProps(false)}<w:r><w:rPr><w:rFonts w:ascii="Noto Sans CJK TC" w:hAnsi="Noto Sans CJK TC" w:eastAsia="Noto Sans CJK TC"/><w:sz w:val="22"/><w:lang w:val="zh-TW" w:eastAsia="zh-TW"/></w:rPr>${s.replace(/\r\n?/g,'\n').split('\n').map(line=>line.split('\t').map(part=>`<w:t xml:space="preserve">${xmlText(part)}</w:t>`).join('<w:tab/>')).join('<w:br/>')}</w:r></w:p>`;}
// Width matches the reference's A4 usable width, without copying its private content.
const TABLE_WIDTH=8306,CELL_WIDTH=4153,IMAGE_WIDTH=4009,IMAGE_HEIGHT=3007;
function drawing(id,width,height){const scale=Math.min(IMAGE_WIDTH/width,IMAGE_HEIGHT/height),cx=Math.round(width*scale*635),cy=Math.round(height*scale*635);return `<w:drawing><wp:inline distT="0" distB="0" distL="0" distR="0"><wp:extent cx="${cx}" cy="${cy}"/><wp:docPr id="${id}" name="Photo ${id}"/><wp:cNvGraphicFramePr><a:graphicFrameLocks noChangeAspect="1"/></wp:cNvGraphicFramePr><a:graphic><a:graphicData uri="http://schemas.openxmlformats.org/drawingml/2006/picture"><pic:pic><pic:nvPicPr><pic:cNvPr id="${id}" name="image${id}.jpg"/><pic:cNvPicPr/></pic:nvPicPr><pic:blipFill><a:blip r:embed="image${id}"/><a:stretch><a:fillRect/></a:stretch></pic:blipFill><pic:spPr><a:xfrm><a:off x="0" y="0"/><a:ext cx="${cx}" cy="${cy}"/></a:xfrm><a:prstGeom prst="rect"><a:avLst/></a:prstGeom></pic:spPr></pic:pic></a:graphicData></a:graphic></wp:inline></w:drawing>`;}
export async function photoTableDocx(groups){const plan=tablePlan(groups),media=[],relations=[`<Relationship Id="styles" Type="${officeRel}/styles" Target="styles.xml"/>`];let nextId=0;const rows=plan.map(row=>{if(row.kind==='description')return `<w:tr><w:tc><w:tcPr><w:tcW w:w="${TABLE_WIDTH}" w:type="dxa"/><w:gridSpan w:val="2"/></w:tcPr>${descriptionParagraph(row.engineering)}</w:tc></w:tr>`;const cells=[0,1].map(i=>{const photo=row.photos[i];let content='';if(photo){if(!(photo.blob instanceof Blob)||photo.blob.type!=='image/jpeg'||!Number.isFinite(photo.width)||!Number.isFinite(photo.height)||photo.width<=0||photo.height<=0)throw Error('匯出影像無效');const id=++nextId;media.push([`word/media/image${id}.jpg`,photo.blob]);relations.push(`<Relationship Id="image${id}" Type="${officeRel}/image" Target="media/image${id}.jpg"/>`);content=`<w:r>${drawing(id,photo.width,photo.height)}</w:r>`;}return `<w:tc><w:tcPr><w:tcW w:w="${CELL_WIDTH}" w:type="dxa"/><w:vAlign w:val="center"/></w:tcPr><w:p><w:pPr><w:jc w:val="center"/><w:spacing w:before="0" w:after="0"/>${row.keepNext?'<w:keepNext/>':''}</w:pPr>${content}</w:p></w:tc>`;}).join('');return `<w:tr><w:trPr><w:cantSplit/><w:trHeight w:val="3200" w:hRule="atLeast"/></w:trPr>${cells}</w:tr>`;}).join('');
 const border=['top','left','bottom','right','insideH','insideV'].map(edge=>`<w:${edge} w:val="single" w:sz="4" w:color="000000"/>`).join('');
 const documentXML=xmlHeader+`<w:document xmlns:w="${W}" xmlns:r="${officeRel}" xmlns:wp="http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing" xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" xmlns:pic="http://schemas.openxmlformats.org/drawingml/2006/picture"><w:body><w:tbl><w:tblPr><w:tblW w:w="${TABLE_WIDTH}" w:type="dxa"/><w:tblLayout w:type="fixed"/><w:tblBorders>${border}</w:tblBorders><w:tblCellMar><w:top w:w="72" w:type="dxa"/><w:bottom w:w="72" w:type="dxa"/><w:left w:w="72" w:type="dxa"/><w:right w:w="72" w:type="dxa"/></w:tblCellMar></w:tblPr><w:tblGrid><w:gridCol w:w="${CELL_WIDTH}"/><w:gridCol w:w="${CELL_WIDTH}"/></w:tblGrid>${rows}</w:tbl><w:p><w:pPr><w:spacing w:before="0" w:after="0" w:line="20" w:lineRule="exact"/></w:pPr><w:r><w:rPr><w:sz w:val="2"/></w:rPr></w:r></w:p><w:sectPr><w:pgSz w:w="11906" w:h="16838"/><w:pgMar w:top="709" w:bottom="709" w:left="1800" w:right="1800" w:header="0" w:footer="0"/></w:sectPr></w:body></w:document>`;
 const stylesXML=xmlHeader+`<w:styles xmlns:w="${W}"><w:docDefaults><w:rPrDefault><w:rPr><w:rFonts w:ascii="Noto Sans CJK TC" w:hAnsi="Noto Sans CJK TC" w:eastAsia="Noto Sans CJK TC"/><w:sz w:val="22"/><w:szCs w:val="22"/><w:lang w:val="zh-TW" w:eastAsia="zh-TW"/></w:rPr></w:rPrDefault><w:pPrDefault>${pProps(false)}</w:pPrDefault></w:docDefaults><w:style w:type="paragraph" w:default="1" w:styleId="Normal"><w:name w:val="Normal"/></w:style></w:styles>`;
 const contentTypes=xmlHeader+'<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Default Extension="jpg" ContentType="image/jpeg"/><Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/><Override PartName="/word/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.styles+xml"/></Types>';
 return zipStore([['[Content_Types].xml',new Blob([contentTypes])],['_rels/.rels',new Blob([xmlHeader+`<Relationships xmlns="${relNS}"><Relationship Id="document" Type="${officeRel}/officeDocument" Target="word/document.xml"/></Relationships>`])],['word/document.xml',new Blob([documentXML])],['word/styles.xml',new Blob([stylesXML])],['word/_rels/document.xml.rels',new Blob([xmlHeader+`<Relationships xmlns="${relNS}">${relations.join('')}</Relationships>`])],...media]);}
function abortCheck(signal){if(signal?.aborted)throw new DOMException('匯出已取消','AbortError');}
export async function exportJpeg(photo,original,signal){abortCheck(signal);if(!(original instanceof Blob)||!original.size)throw Error('原始照片未取得');const im=new Image(),url=URL.createObjectURL(original);let onAbort,canvas;try{im.src=url;await Promise.race([im.decode(),new Promise((_,reject)=>{onAbort=()=>reject(new DOMException('匯出已取消','AbortError'));signal?.addEventListener('abort',onAbort,{once:true});if(signal?.aborted)onAbort();})]);abortCheck(signal);const w=im.naturalWidth,h=im.naturalHeight;if(!w||!h||w*h>80000000)throw Error('照片過大或無法解碼');const rotation=previewRotation(photo,w,h),swapped=rotation%180!==0,ow=swapped?h:w,oh=swapped?w:h,scale=Math.min(1,1600/Math.max(ow,oh));canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(ow*scale));canvas.height=Math.max(1,Math.round(oh*scale));const ctx=canvas.getContext('2d');if(!ctx)throw Error('無法建立匯出影像');ctx.fillStyle='#fff';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.translate(canvas.width/2,canvas.height/2);ctx.rotate(rotation*Math.PI/180);ctx.drawImage(im,-w*scale/2,-h*scale/2,w*scale,h*scale);const blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/jpeg',.9));abortCheck(signal);if(!blob||blob.type!=='image/jpeg')throw Error('瀏覽器無法產生 Word 使用的 JPEG');return {blob,width:canvas.width,height:canvas.height,rotation,photoId:photo.id};}finally{signal?.removeEventListener('abort',onAbort);URL.revokeObjectURL(url);im.src='';if(canvas)canvas.width=canvas.height=1;}}
export async function preparePhotoGroups(snapshot,groupIds,{signal,onProgress=()=>{}}={}){if(!groupIds.length||new Set(groupIds).size!==groupIds.length)throw Error('請選取不重複的紀錄集');const photos=new Map(snapshot.photos.map(p=>[p.id,p])),assets=new Map(snapshot.assets.map(a=>[a.id,a.original])),groups=new Map(snapshot.groups.map(g=>[g.id,g]));const chosen=groupIds.map(id=>{const g=groups.get(id);if(!g)throw Error('紀錄集已不存在，請重新開啟匯出');validateGroup(g,new Set(photos.keys()));xmlText(g.engineering);return g;});const total=chosen.reduce((n,g)=>n+g.photoIds.length,0);if(total>300)throw Error('照片數過多，請分批匯出');const result=[];let count=0,bytes=0;for(const g of chosen){const encoded=[];for(const id of g.photoIds){abortCheck(signal);onProgress(++count,total);let image;try{image=await exportJpeg(photos.get(id),assets.get(id),signal);}catch(e){if(e.name==='AbortError')throw e;throw Error(`照片 ${photos.get(id)?.photoNumber??'?'} 無法匯出：${e.message}`);}bytes+=image.blob.size;if(bytes>32*1048576)throw Error('匯出影像超過 32 MB，請減少組數分次匯出');encoded.push(image);}result.push({id:g.id,engineering:g.engineering,photos:encoded});}return result;}
